spring:
  application:
    name: "weixin-gataway"  
  cloud:
    gateway:
      routes:
  data:
    redis:
      port: 6379 # Env: ${SPRING_DATA_REDIS_PORT}
      password: '' # Env: ${SPRING_DATA_REDIS_PASSWORD}
      host: localhost # Env: ${SPRING_DATA_REDIS_HOST}
  session:
    redis:
      flush-mode: ON_SAVE
      namespace: spring:s:codefarme:weixin-gataway
    store-type: redis
weixin:
  mp:
    appId: ${WEIXIN_MP_APPID}
    appSecret: ${WEIXIN_MP_APPSECRET}
    uris:
      jscode2session: "https://api.weixin.qq.com/sns/jscode2session"
      token: "https://api.weixin.qq.com/cgi-bin/token"
      userphonenumber: "https://api.weixin.qq.com/wxa/business/getuserphonenumber"
server:
  error:
    include-stacktrace: ON_PARAM
---
spring:
  config:
    activate:
      on-profile: prod
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: NEVER
springdoc:
  api-docs:
    enabled: 'false' # Disabling the /v3/api-docs endpoint
  swagger-ui:
    enabled: 'false' # Disabling the swagger-ui

